### ISSUE TITLE
List of components to be created

### ISSUE THREAD

**Issue by idantb101** [FACN3/parkapp#14]
- [x] one box of park in the parks list @idantb101
- [x] list of all the parks @idantb101
- [x] map @haithhawk
- [x] navbar @sophieeejw
- [x] single park detail page @NickP123
- [ ] setting rating (stars) on single park detail page 
- [ ] like button on single park detail page

**Comment by sophiavocado** [comment]
Create a new issue for each component, and also please add your github handle next to the list on this issue so we know who works on what! 🙂

**Comment by sophiavocado** [comment]
the last two features -> stretch goals
