### ISSUE TITLE
Pushing to Heroku

### ISSUE THREAD

**Issue by matthewdking** [FACN3/parkapp#29]
I would advise pushing to Heroku early on so you don't have problems later on at the end of the project. This has the added benefit that you can send links to the client of a published site and show them your progress that they can click through :+1: 

Before pushing to Heroku add a script to your `package.json` then you're good to go :rocket: 
```
"heroku-postbuild": "npm run build"
```

**Comment by matthewdking** [comment]
Add a link to your README #11

**Comment by sophiavocado** [comment]
#47 done
