### ISSUE TITLE
urgent issues to be fixed before presentation

### ISSUE THREAD

**Issue by idantb101** [FACN3/parkapp#52]
- [x] processing search query into lower cases/no space in between @sophieeejw
- [x] park picture sticking out from the box on desktop mode (park boxes) @sophieeejw
- [x] hide filter options (second navbar) on map page. @sophieeejw
- [x] fix search box in map page. @sophieeejw
- [x] link each park to detail page. @idantb101 
- [x] add arabic data to real db @sophieeejw
- [x] get data from real db. @sophieeejw
- [x] waze link. 
- [x] link detail page to map page.

**Comment by NickP123** [comment]
All issues are completed - closing.  Thanks team!
