### ISSUE TITLE
Client - Discussion points & Feedback

### ISSUE THREAD

**Issue by NickP123** [FACN3/parkapp#8]
**1)** We would like to demonstrate the mock-up that we have made, to get your feedback as a user. The mock-up is focused on National Parks, but the interface can easily be transferred to an app just focused on city parks. We would like to agree how to move forward - either focusing on National Parks or City Parks.

**2)** The goal of the project was to improve access to parks for the Arab community. We would like to see the Arabic park data that is available from the Galilee Society so that we can see how this can be used in the app. Could you please arrange. 

**3)** Discuss providing administrator access to our app so that in the future it can be populated  with more data in Arabic which will beyond the scope of what we can achieve in 3 weeks to get a useable MVP (Minimal Viable Product).

Thank you, Nick and the team.

**Comment by Amiraarraf** [comment]
first, I think we should agree on how much parks we can currently add to the map. I suggest to start with only City parks. and I suggest to choose 7 major cities. Haifa, Acre, Jerusalem, Tel-Aviv Yaffo, Affola, Nazareth and Ber-Sheva. 

we suggest to have limited and short information about each park. we will provide you a website that includes these information. now, my question is possible to use google translate to give us the translation for the data? for example: 
https://goo.gl/Hp48jm 

the first table is what we need to extract from each part website. ( we can review the translated data) 

what do you think about it and what do you suggest? 

Amira

**Comment by sophiavocado** [comment]
Hello Amira! Thank you for your suggestion.

At this moment, we are still working on building all the necessary functionalities using mock up data.  Once we finish the initial building(hopefully by the end of this week), we will be focusing on data processing part and get back to you for further information! :)

Thank you!

**Comment by NickP123** [comment]
Hi Amira,

I hope you've had a good week? We just wanted to update you on where we are with our project

In your last message you mentioned choosing City Parks. When we met, we discussed using National Parks. Can you confirm which you'd like us to focus on so that we can include the right information in our application? At this time we suggest going with one or the other, but not both.

You also asked about Google Translate. This will not give you the quality of data you would need in Arabic for the project. You would need to explore other options for this. 

**Progress**
Progress this week has been good and we now have a working front-end for our project and have today created our database for storing all the park information. 

**Link to Hosted Site**
We have a working link for our project which we are hosting on Heroku. This is not the final version of course, but is a live link to what we have done so far 

Should you have any feedback, then please do let us know here.

The link to the project is: https://parkappfac.herokuapp.com/

**Plan for Next Week**
- Import some basic level information into the database for 10 parks (either National or City - TBC with the client) and user test
- Address any bugs prior to production
- Stretch Goal - administrative functionality for the application so the client can manage the database securely
 
Thanks. Team Park.

**Comment by Amiraarraf** [comment]
Dear Nick and the team, Thanks for the update. It's actually impressing. 
After consultung with the staff in the Galilee Society we thought to start with City Parks. 
We thought you can import easily the information from Inature site. I absolutely agree that google translate doesn't give accurate results therefore we suggested we can do the editing to the texts. 
Please let me know what which is the easier way to do it but yet to get good results. 
Have a nice weekend
